{
    'name': 'Bookstore SJ',
    'version': '1.0',
    'summary': 'Summery',
    'description': 'Description',
    'category': 'commprog',
    'author': 'Author',
    'website': 'web',
    'depends': ['base', 'board', 'mail', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/bookstore_sequence_view.xml',
        'views/book_view.xml',
        'views/author_view.xml',
        'views/publisher_view.xml',
        'views/category_view.xml',
        'views/invoice_view.xml',
        'views/dashboard_view.xml',
        'views/tags_view.xml',
        'views/employee_view.xml',
        'wizard/invoicesj_report.xml',
        'report/invoicesj_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
