{
    'name': 'Configurations',
    'version': '1.0.0',
    'category': 'Configurations',
    'author': 'Esat Elezi',
    'sequence': '-101',
    'summary': 'Configurations for a School Management System',
    'description': 'Configurations',
    'depends': ['mail'],
    'data': [
        'views/grades_view.xml',
        'views/event_type_view.xml',
        'views/subjects_view.xml',
        'views/school_grade_interval_view.xml',
        'views/academic_years_view.xml',
        'views/academic_quarters_view.xml',
        'views/menu.xml',
        'data/month_preloaded.xml',
        'email_templates/mail_template_data.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
